blank_issues_enabled: false
contact_links:
  - name: Dúvidas sobre o Álbum ou Repertório
    url: https://foxnove.github.io/mesmo-tarde/
    about: Acesse o Cifra Fox para visualizar letras, cifras e contatos
